name: ServiceNow DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ServiceNow DevOps Change
        uses: ServiceNow/servicenow-devops-change@v6.1.0

        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}

          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}

          context-github: ${{ toJSON(github) }}

          job-name: 'deploy'

          devops-integration-user-name: ${{ secrets.SN_USERNAME }}

          devops-integration-user-password: ${{ secrets.SN_PASSWORD }}

      - name: Success Message
        run: echo "Deployment Completed Successfully"
