name: ServiceNow DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running Tests"
          python --version

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ServiceNow DevOps Change
        uses: ServiceNow/servicenow-devops-change@v6.1.0

        with:
          instance-url: ${{ secrets.SN_INSTANCE_URL }}

          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}

          context-github: ${{ toJSON(github) }}

          job-name: 'Deploy Stage'

          devops-integration-user-name: ${{ secrets.SN_USERNAME }}

          devops-integration-user-password: ${{ secrets.SN_PASSWORD }}

          change-request: >
            {
              "attributes": {
                "short_description": "GitHub Deployment in Demo Call",
                "description": "Automated CRQ from GitHub Actions"
              }
            }

      - name: Deploy Application
        run: |
          echo "Deploying Application"

      - name: Success Message
        run: |
          echo "Deployment Completed Successfully"
